#
# MFA Makefile.version
#
# GNU Make required
#

# Update version string when a release is made
VERSION = 180420

# server info version, each cannot be more than a byte's value
SVINFO_VERSION_YR = 18
SVINFO_VERSION_SV = 0
